! MATH: V2M ====================================================================  
! **** PURPOSE ****
! THIS CODE TRANSFORMS A VECTOR TO DIAGONAL MATRIX
! **** INPUT VARIABLES ****
! []
! **** OUTPUT VARIABLES ****
! 
! **** VERSION ****
! JAN/29/2014 FIRST BUILT 

! **** COMMENT **** 

SUBROUTINE PI_DIAG_RV2M(A,A_DIM,B,B_DIM)
	IMPLICIT NONE
	! DIMENSION
	INTEGER,INTENT(IN) :: A_DIM, B_DIM(2)
	! INPUT
	REAL,INTENT(IN) :: A(A_DIM)
	! OUTPUT
	REAL,INTENT(OUT) :: B(B_DIM(1),B_DIM(2))
	! LOCAL(DUMMY)
	INTEGER :: N
	
	! VARIABLE INITIALIZATION
	B=0 ! OUTPUT
	FORALL(N=1:A_DIM) B(N,N)=A(N)
END SUBROUTINE

SUBROUTINE PI_DIAG_CV2M(A,A_DIM,B,B_DIM)
	IMPLICIT NONE
	! DIMENSION
	INTEGER,INTENT(IN) :: A_DIM, B_DIM(2)
	! INPUT
	COMPLEX,INTENT(IN) :: A(A_DIM)
	! OUTPUT
	COMPLEX,INTENT(OUT) :: B(B_DIM(1),B_DIM(2))
	! LOCAL(DUMMY)
	INTEGER :: N
	
	! VARIABLE INITIALIZATION
	B=0.0 ! OUTPUT
	FORALL(N=1:A_DIM) B(N,N)=A(N)
END SUBROUTINE

SUBROUTINE PI_DIAG_RM2V(A,A_DIM,B,B_DIM)
	IMPLICIT NONE
	! DIMENSION
	INTEGER,INTENT(IN) :: A_DIM(2), B_DIM
	! INPUT
	REAL,INTENT(IN) :: A(A_DIM(1),A_DIM(2))
	! OUTPUT
	REAL,INTENT(OUT) :: B(B_DIM)
	! LOCAL(DUMMY)
	INTEGER :: N
	
	! VARIABLE INITIALIZATION
	B=0.0 ! OUTPUT
	FORALL(N=1:A_DIM(1)) B(N)=A(N,N)
END SUBROUTINE

SUBROUTINE PI_DIAG_CM2V(A,A_DIM,B,B_DIM)
	IMPLICIT NONE
	! DIMENSION
	INTEGER,INTENT(IN) :: A_DIM(2), B_DIM
	! INPUT
	COMPLEX,INTENT(IN) :: A(A_DIM(1),A_DIM(2))
	! OUTPUT
	COMPLEX,INTENT(OUT) :: B(B_DIM)
	! LOCAL(DUMMY)
	INTEGER :: N
	
	! VARIABLE INITIALIZATION
	B=0.0 ! OUTPUT
	FORALL(N=1:A_DIM(1)) B(N)=A(N,N)
END SUBROUTINE