! READ RMAT ====================================================================  
! **** PURPOSE ****
! READ THE DATA THAT OUTPUT FORM PI_PRINT_RMAT STANDARD FORMAT 
! **** INPUT VARIABLES ****
! [READ_TYPE]: 'O' (ORIGINAL) 'T' (TRANSPOSE)
! [FID]: YOUR FILE ID
! **** OUTPUT VARIABLES ****
! [A]: REAL / COMPLEX / INTEGER, NXM, THE MATRIX TO OUTPUT
! **** VERSION ****
! FEB/1/2014
! **** COMMENT **** 
! 1. USE 'T' OPTION TO TRANPOSE YOUR PRINT AUTOMATICALLY
! 2. IF YOU'RE READING A VETOR, A_DIM HAS TO BE WRITTEN AS
! (/SHAPE(A),1/) TO PRETENT IT AS A MATRIX!

SUBROUTINE PI_READ_RMAT(FID,READ_TYPE,A,A_DIM)
	IMPLICIT NONE
	! DIMENSION 
	INTEGER, INTENT(IN) :: A_DIM(2)
	! INPUT 
	INTEGER :: FID
	CHARACTER(LEN=*), INTENT(IN) :: READ_TYPE
	! OUTPUT
	REAL, INTENT(OUT) :: A(A_DIM(1),A_DIM(2))
	! LOCAL 
	INTEGER :: N,ORDER
	CHARACTER(LEN=30) :: READ_FORM
	
	READ(FID,*)
	READ(FID,"(I4)") ORDER
	READ(FID,*)
	READ(FID,*)
	READ(FID,*)
	SELECT CASE(READ_TYPE)
	CASE('O')
		WRITE(READ_FORM,*) "(",A_DIM(2),"(2X,F9.5))"
		DO N=1,A_DIM(1)
			READ(FID,READ_FORM) A(N,:) 
		END DO
		A=A*(10.0**(ORDER))
	CASE('T')
		WRITE(READ_FORM,*) "(",A_DIM(1),"(2X,F9.5))"
		DO N=1,A_DIM(2)
			READ(FID,READ_FORM) A(:,N) 
		END DO
		A=A*(10.0**(ORDER))
	END SELECT
END SUBROUTINE

! CMAT -----------------------------------------------------
SUBROUTINE PI_READ_CMAT(FID,READ_TYPE,A,A_DIM)
	IMPLICIT NONE
	! DIMENSION 
	INTEGER, INTENT(IN) :: A_DIM(2)
	! INPUT 
	INTEGER :: FID
	CHARACTER(LEN=*), INTENT(IN) :: READ_TYPE
	! OUTPUT
	COMPLEX, INTENT(OUT) :: A(A_DIM(1),A_DIM(2))
	! LOCAL 
	INTEGER :: N,ORDER
	CHARACTER(LEN=30) :: READ_FORM
	
	READ(FID,*)
	READ(FID,"(I4)") ORDER
	READ(FID,*)
	READ(FID,*)
	READ(FID,*)
	SELECT CASE(READ_TYPE)
	CASE('O')
		WRITE(READ_FORM,*) "(",A_DIM(2),"(2X,F9.5,F9.5))"
		DO N=1,A_DIM(1)
			READ(FID,READ_FORM) A(N,:) 
		END DO
		A=A*(10.0**(ORDER))
	CASE('T')
		WRITE(READ_FORM,*) "(",A_DIM(1),"(2X,F9.5,F9.5))"
		DO N=1,A_DIM(2)
			READ(FID,READ_FORM) A(:,N) 
		END DO
		A=A*(10.0**(ORDER))
	END SELECT
END SUBROUTINE

! IMAT --------------------------------
SUBROUTINE PI_READ_IMAT(FID,READ_TYPE,A,A_DIM)
	IMPLICIT NONE
	! DIMENSION 
	INTEGER, INTENT(IN) :: A_DIM(2)
	! INPUT 
	INTEGER :: FID
	CHARACTER(LEN=*), INTENT(IN) :: READ_TYPE
	! OUTPUT
	INTEGER, INTENT(OUT) :: A(A_DIM(1),A_DIM(2))
	! LOCAL 
	INTEGER :: N,ORDER
	CHARACTER(LEN=30) :: READ_FORM
	
	READ(FID,*)
	READ(FID,"(I4)") ORDER
	READ(FID,*)
	READ(FID,*)
	READ(FID,*)
	SELECT CASE(READ_TYPE)
	CASE('O')
		WRITE(READ_FORM,*) "(",A_DIM(2),"(2X,I6))"
		DO N=1,A_DIM(1)
			READ(FID,READ_FORM) A(N,:) 
		END DO
		A=A*(10.0**(ORDER))
	CASE('T')
		WRITE(READ_FORM,*) "(",A_DIM(1),"(2X,I6))"
		DO N=1,A_DIM(2)
			READ(FID,READ_FORM) A(:,N) 
		END DO
		A=A*(10.0**(ORDER))
	END SELECT
END SUBROUTINE