! THIS FILES CONTAINS ALL I/O SUBROUTINES

! PRINT RMAT ====================================================================  
! **** PURPOSE ****
! PRINT OUT THE INPUT REAL MATRIX
! **** INPUT VARIABLES ****
! [DESC]: CHARACTER, DESCRIPTION OF YOUR DATA
! [A]: REAL / COMPLEX / INTEGER, NXM, THE MATRIX 
! [OUT_TYPE]: 'O' (ORIGINAL) 'T' (TRANSPOSE)
! [FID]: YOUR FILE ID OR USE 6 FOR SCREEN PRINT OUT
! **** OUTPUT VARIABLES ****
! N/A
! **** VERSION ****
! JAN/21/2014 FIRST BUILT 
! JAN/27/2014 FIXED COLUMN NUMBER PROBLEM (CHANGE F--> G)
! JAN/28/2014 ADD 'OUT_TYPE' OPTION TO TRANSPOSE PRINT AUTOMATICALLY
! **** COMMENT **** 
! 1. USE FID=6 TO SHOW ON SCREEN
! USE OPEN(UNIT=10,FILE='YOUR_FILE.TXT') TO SHOW IN FILE
! 2. ALL DATA ARE SHOWN BY A VALUE LESS THAN. THE ORDER OF 
! THEM WILLL BE SHOWN IN THE HEADER
! 3. USE 'T' OPTION TO TRANPOSE YOUR PRINT AUTOMATICALLY
! 4. IF YOU'RE PRINTING A VETOR, A_DIM HAS TO BE WRITTEN AS
! (/1,SHAPE(A)/) TO PRETENT IT AS A MATRIX!

SUBROUTINE PI_PRINT_RMAT( DESC, A,A_DIM, OUT_TYPE, FID  )
  IMPLICIT NONE
  CHARACTER*(*)    DESC, OUT_TYPE
  CHARACTER(LEN=30) OUT_FORM
  INTEGER          FID, A_DIM(2)
  REAL             A( A_DIM(1), A_DIM(2) )
  INTEGER          I, J,ORDER, PRINT_DIM(2)
  REAL,ALLOCATABLE :: PRINT_ROW(:) 
  INTEGER, ALLOCATABLE ::C_NUM(:)

  SELECT CASE(OUT_TYPE)
	CASE('O')
		ALLOCATE(C_NUM(A_DIM(2)))
		PRINT_DIM=(/A_DIM(1),A_DIM(2) /)
	CASE('T')
		ALLOCATE(C_NUM(A_DIM(1)))
		PRINT_DIM=(/A_DIM(2),A_DIM(1)/)
  END SELECT
  ALLOCATE(PRINT_ROW(PRINT_DIM(2)))
  
  DO I=1,PRINT_DIM(2)
    C_NUM(I)=I
  END DO
  ORDER=LOG10(MAXVAL(ABS(A)))
  WRITE(FID,*) DESC,", ORDER="  
  WRITE(FID,"(I4)") ,ORDER
  WRITE(FID,*) "************************************************"
  WRITE(OUT_FORM,*) "(",PRINT_DIM(2),"(2XG9.0))"
  WRITE(FID,OUT_FORM) (C_NUM)
  WRITE(FID,*) 
  WRITE(OUT_FORM,*) "(",PRINT_DIM(2),"(2XF9.5))"
  DO I = 1, PRINT_DIM(1)
	SELECT CASE(OUT_TYPE)
	CASE('O')
		PRINT_ROW=A(I,:)
		WRITE(FID,OUT_FORM) PRINT_ROW/10.0**ORDER
	CASE('T')
		PRINT_ROW=A(:,I)
		WRITE(FID,OUT_FORM) PRINT_ROW/10.0**ORDER
	END SELECT     
  END DO
END SUBROUTINE

! PRINT CMAT ====================================================================  

SUBROUTINE PI_PRINT_CMAT(DESC,A,A_DIM, OUT_TYPE, FID )
  IMPLICIT NONE
  CHARACTER(LEN=*)    DESC, OUT_TYPE
  CHARACTER(LEN=30) OUT_FORM
  INTEGER          FID, A_DIM(2)
  COMPLEX          A( A_DIM(1), A_DIM(2) )
  INTEGER          I, J, ORDER, PRINT_DIM(2)
  COMPLEX, ALLOCATABLE :: PRINT_ROW(:) 
  INTEGER, ALLOCATABLE ::C_NUM(:)

  SELECT CASE(OUT_TYPE)
	CASE('O')
		ALLOCATE(C_NUM(A_DIM(2)))
		PRINT_DIM=(/A_DIM(1),A_DIM(2) /)
	CASE('T')
		ALLOCATE(C_NUM(A_DIM(1)))
		PRINT_DIM=(/A_DIM(2),A_DIM(1)/)
  END SELECT
  ALLOCATE(PRINT_ROW(PRINT_DIM(2)))
  
  DO I=1,PRINT_DIM(2)
    C_NUM(I)=I
  END DO
  ORDER=LOG10(MAXVAL(ABS(A)))
  WRITE(FID,*) DESC,", ORDER="  
  WRITE(FID,"(I4)") ,ORDER
  WRITE(FID,*) "************************************************"
  WRITE(OUT_FORM,*) "(",PRINT_DIM(2),"(2XG18.0))"
  WRITE(FID,OUT_FORM) (C_NUM)
  WRITE(FID,*) 
  WRITE(OUT_FORM,*) "(",PRINT_DIM(2),"(2X,F9.5,F9.5))"
  DO I = 1, PRINT_DIM(1)
	SELECT CASE(OUT_TYPE)
	CASE('O')
		PRINT_ROW=A(I,:)
		WRITE(FID,OUT_FORM) PRINT_ROW/10.0**ORDER
	CASE('T')
		PRINT_ROW=A(:,I)
		WRITE(FID,OUT_FORM) PRINT_ROW/10.0**ORDER
	END SELECT     
  END DO
END SUBROUTINE

! PRINT IMAT ====================================================================  

SUBROUTINE PI_PRINT_IMAT(DESC,A,A_DIM, OUT_TYPE,FID )
  IMPLICIT NONE
  CHARACTER(LEN=*)   :: DESC, OUT_TYPE
  CHARACTER(LEN=30) :: OUT_FORM
  INTEGER ::         FID, A_DIM(2)
  INTEGER ::         A( A_DIM(1), A_DIM(2) )
  INTEGER ::         I, PRINT_DIM(2)
  INTEGER, ALLOCATABLE :: PRINT_ROW(:) 
  INTEGER, ALLOCATABLE ::C_NUM(:)
  
  SELECT CASE(OUT_TYPE)
	CASE('O')
		ALLOCATE(C_NUM(A_DIM(2)))
		PRINT_DIM=(/A_DIM(1),A_DIM(2) /)
	CASE('T')
		ALLOCATE(C_NUM(A_DIM(1)))
		PRINT_DIM=(/A_DIM(2),A_DIM(1)/)
  END SELECT
  ALLOCATE(PRINT_ROW(PRINT_DIM(2)))

  DO I=1,PRINT_DIM(2)
    C_NUM(I)=I
  END DO

  WRITE(FID,*) DESC,", ORDER="  
  WRITE(FID,"(I4)") 0
  WRITE(FID,*) "************************************************"
  WRITE(OUT_FORM,*) "(",PRINT_DIM(2),"(2X,I6))"
  WRITE(FID,OUT_FORM) (C_NUM)
  WRITE(FID,*) 
  WRITE(OUT_FORM,*) "(",PRINT_DIM(2),"(2X,I6))"
  DO I = 1, PRINT_DIM(1)
	SELECT CASE(OUT_TYPE)
	CASE('O')
		PRINT_ROW=A(I,:)
		WRITE(FID,OUT_FORM) PRINT_ROW
	CASE('T')
		PRINT_ROW=A(:,I)
		WRITE(FID,OUT_FORM) PRINT_ROW
	END SELECT  
  END DO
END SUBROUTINE