! PI_EIG_RMAT =================================================================
! **** PURPOSE ****
! THIS CODE DIAGONALIZE A SYMMETRY/HERMITIAN MATRIX USING MRRR ALGORITHM IN LAPACK
! (SSYEVR, CHEEVR)
! **** INPUT VARIABLES ****
! [A]: REAL, NXN, THE MATRIX TO BE DIAGONALIZED  
! [LB]: REAL, 1, THE LOWER BOUND OF YOUR EIGENSTATE
! [UB]: REAL, 1, THE UPPER BOUND OF YOUR EIGENSTATE
! [BOUND_OPT]: 'A'(ALL),'I'(INDEX),'V'(VALUE)
! **** OUTPUT VARIABLES ****
! [EVAL]: REAL, N, THE EIGENVALUES 
! [EVEC]: REAL, NXM, EIGENVETORS
! **** VERSION ****
! 2/6/2014 FIRST BUILT 
! **** COMMENT **** 
! 1. LB, UP
! IF BOUND_OPT='A', THEY ARE NOT REFERENCE. IF 'I', THEY WILL BE CONSIDER
! AS EIGENVALUE INDEX. NINT(LB), NINT(UB) WILL BE TAKEN. IF 'V', THEY WILL
! BE CONSIDER AS VALUES.

SUBROUTINE PI_EIGR_SYMAT(A,A_DIM,BOUND,BOUND_OPT,TOT_EIG,EVAL,EVAL_DIM,EVEC,EVEC_DIM)
	IMPLICIT NONE
	! DIMENSION 
	INTEGER, INTENT(IN) :: A_DIM(2), EVAL_DIM, EVEC_DIM(2)
	! INPUT
	REAL, INTENT(IN) :: A(A_DIM(1),A_DIM(2)), BOUND(2)
	CHARACTER(LEN=*), INTENT(IN) :: BOUND_OPT 
	! OUTPUT
	INTEGER, INTENT(OUT) :: TOT_EIG
	REAL, INTENT(OUT) :: EVAL(EVAL_DIM), EVEC(EVEC_DIM(1),EVEC_DIM(2))
	! LOCAL(VALUE)
	INTEGER :: LWORK, LIWORK, INFO
	! LOCAL(ARRAY)
	INTEGER :: ISUPPZ(2*EVEC_DIM(2))
	! ALLOCATABEL
	REAL, ALLOCATABLE :: WORK(:)
	INTEGER, ALLOCATABLE :: IWORK(:)
	
	IF (EVAL_DIM/=A_DIM(1)) THEN
		WRITE(*,*) "ERROR IN PI_EIGR_SYMAT! DIMENSIONS ARE INCONSISTENT!"
	END IF
	
	
	ALLOCATE(WORK(1))
	ALLOCATE(IWORK(1))
	LWORK=-1
	LIWORK=-1
	CALL SSYEVR('V',BOUND_OPT,'U',A_DIM(1),A,A_DIM(1),BOUND(1),BOUND(2)&
	&,NINT(BOUND(1)),NINT(BOUND(2)),-1.0,TOT_EIG,EVAL&
	&,EVEC,EVEC_DIM(1),ISUPPZ,WORK,LWORK,IWORK,LIWORK,INFO)
	LWORK=NINT(WORK(1))+1
	LIWORK=IWORK(1)+1
	DEALLOCATE(WORK)
	DEALLOCATE(IWORK)
	ALLOCATE(WORK(LWORK))
	ALLOCATE(IWORK(LIWORK))
	
	CALL SSYEVR('V',BOUND_OPT,'U',A_DIM(1),A,A_DIM(1),BOUND(1),BOUND(2)&
	&,NINT(BOUND(1)),NINT(BOUND(2)),-1,TOT_EIG,EVAL&
	&,EVEC,EVEC_DIM(1),ISUPPZ,WORK,LWORK,IWORK,LIWORK,INFO)
	
	IF (INFO/=0) THEN
		WRITE(*,*) "ERROR IN PI_EIGR_SYMAT! INFO/=0!"
		RETURN
	END IF
END SUBROUTINE
	
! PI_EIG_RMAT =================================================================
! **** INPUT VARIABLES ****
! [A]: COMPLEX, NXN, THE MATRIX TO BE DIAGONALIZED  
! [LB]: REAL, 1, THE LOWER BOUND OF YOUR EIGENSTATE
! [UB]: REAL, 1, THE UPPER BOUND OF YOUR EIGENSTATE
! **** OUTPUT VARIABLES ****
! [EVAL]: REAL, N, THE EIGENVALUES 
! [EVEC]: COMPLEX, NXM, EIGENVETORS

SUBROUTINE PI_EIGR_HEMAT(A,A_DIM,BOUND,BOUND_OPT,TOT_EIG,EVAL,EVAL_DIM,EVEC,EVEC_DIM)
	IMPLICIT NONE
	! DIMENSION 
	INTEGER, INTENT(IN) :: A_DIM(2), EVAL_DIM, EVEC_DIM(2)
	! INPUT
	COMPLEX, INTENT(IN) :: A(A_DIM(1),A_DIM(2)) 
	REAL, INTENT(IN) :: BOUND(2)
	CHARACTER(LEN=*), INTENT(IN) :: BOUND_OPT 
	! OUTPUT
	INTEGER, INTENT(OUT) :: TOT_EIG
	REAL, INTENT(OUT) :: EVAL(EVAL_DIM) 
	COMPLEX, INTENT(OUT) :: EVEC(EVEC_DIM(1),EVEC_DIM(2))
	! LOCAL(VALUE)
	INTEGER :: LWORK, LIWORK, LRWORK, INFO
	! LOCAL(ARRAY)
	INTEGER :: ISUPPZ(2*EVEC_DIM(2))
	! ALLOCATABEL
	REAL, ALLOCATABLE ::RWORK(:)
	COMPLEX, ALLOCATABLE :: WORK(:)
	INTEGER, ALLOCATABLE :: IWORK(:)
	
	IF (EVAL_DIM/=A_DIM(1)) THEN
		WRITE(*,*) "ERROR IN PI_EIGR_HEMAT! DIMENSIONS ARE INCONSISTENT!"
	END IF
	
	ALLOCATE(WORK(1))
	ALLOCATE(RWORK(1))
	ALLOCATE(IWORK(1))
	LWORK=-1
	LRWORK=-1
	LIWORK=-1
	CALL CHEEVR('V',BOUND_OPT,'U',A_DIM(1),A,A_DIM(1),BOUND(1),BOUND(2)&
	&,NINT(BOUND(1)),NINT(BOUND(2)),-1,TOT_EIG,EVAL&
	&,EVEC,EVEC_DIM(1),ISUPPZ,WORK,LWORK,RWORK,LRWORK,IWORK,LIWORK,INFO)
	LWORK=NINT(REAL(WORK(1)))+1
	LRWORK=NINT(RWORK(1))+1
	LIWORK=IWORK(1)+1
	DEALLOCATE(WORK)
	DEALLOCATE(RWORK)
	DEALLOCATE(IWORK)
	ALLOCATE(WORK(LWORK))
	ALLOCATE(RWORK(LRWORK))
	ALLOCATE(IWORK(LIWORK))
	
	CALL CHEEVR('V',BOUND_OPT,'U',A_DIM(1),A,A_DIM(1),BOUND(1),BOUND(2)&
	&,NINT(BOUND(1)),NINT(BOUND(2)),-1,TOT_EIG,EVAL&
	&,EVEC,EVEC_DIM(1),ISUPPZ,WORK,LWORK,RWORK,LRWORK,IWORK,LIWORK,INFO)
	
	IF (INFO/=0) THEN
		WRITE(*,*) "ERROR IN PI_EIGR_SYMAT! INFO/=0!"
		RETURN
	END IF
END SUBROUTINE
