! FERMION OPERATOR =============================================================  
! **** PURPOSE ****
! THIS CODE CALCULATES THE FERMION OPERATORS ACTING ON A GIVEN FOCK STATE 
! **** VARIABLES ****
! [FERMION_OP]: INTEGER, 2XN 
!	<= THE FERMION OPERATORS YOU WANT TO PERFORM
! [FOCK_KET]: INTEGER, MX1 
!	<= THE FOCK KET TO BE ACTED
!	=> THE FOCK KET MODIFIED
! [FOCK_PHASE]:
!	=> THE PHASE IN FRONT OF THE OUTPUT FOCK STATE
! **** VERSION ****
! 1/24/2014 FIRST BUILT 
! 2/11/2014 LET INPUT AND OUTPUT FOCK_KET THE SMAE VARIABLE
! **** COMMENT **** 
! 1. FERMION_OP:
! FOR EXAMPLE, WE WANT TO CALCULATE C+(I)C(J), THEN, THEN GIVE A 2X2 MATIRX WITH
! VALUES: /J,-1,I,+1/, IT MEANS, DO DESTORY ON J AND CREATE ON I. (NOTICE: THE
! ORDER IS REVERSED!)
! 2. FOCK_PHASE:
! PHASE OF THE OUTPUT KET. EITHER +1 OR -1. IF THE OPERATORS MAKE THE KET NULL
! PHASE WILL BE SET ZERO. 

SUBROUTINE PI_FERMION_OP(FERMION_OP,FERMION_OP_DIM,FOCK_KET,FOCK_KET_DIM,FOCK_PHASE)
  IMPLICIT NONE
  ! DIMENSION
  INTEGER, INTENT(IN) :: FERMION_OP_DIM(2), FOCK_KET_DIM
  ! VARIABLES
  INTEGER, INTENT(IN) :: FERMION_OP(FERMION_OP_DIM(1),FERMION_OP_DIM(2))
  INTEGER, INTENT(INOUT) :: FOCK_KET(FOCK_KET_DIM)
  INTEGER, INTENT(OUT) :: FOCK_PHASE
  ! LOCAL (DUMMY)
  INTEGER :: N, M, P
  ! LOCAL (VALUE)
  INTEGER :: TOT_OP
  ! LOCAL (ARRAY)
  ! LOCAL (ALLOCATABLE)

  ! VARIABLE INITIALIZATION  
  FOCK_PHASE=0 ! OUTPUT
  TOT_OP=0 ! LOCAL(VALUES)
  ! PROGRAM START -------------------
  
  ! GENERATE ALL VARIABLES
  TOT_OP=FERMION_OP_DIM(2)
  DO N=1,TOT_OP
    SELECT CASE(FERMION_OP(2,N))
    CASE(+1) ! CREATE
      SELECT CASE(FOCK_KET(FERMION_OP(1,N)))
      CASE(+1)
        FOCK_KET=0
        FOCK_PHASE=0
        EXIT
      CASE(0)       
        FOCK_KET(FERMION_OP(1,N))=1
        IF (FERMION_OP(1,N)/=1) THEN
          FOCK_PHASE=(-1)**(SUM(FOCK_KET(1:FERMION_OP(1,N)-1)))
        END IF
      END SELECT 
     CASE(-1) ! DESTORY
      SELECT CASE(FOCK_KET(FERMION_OP(1,N)))
      CASE(0)
        FOCK_KET=0
        FOCK_PHASE=0
        EXIT
      CASE(+1)
        FOCK_KET(FERMION_OP(1,N))=0
        IF (FERMION_OP(1,N)/=1) THEN
          FOCK_PHASE=(-1)**(SUM(FOCK_KET(1:FERMION_OP(1,N)-1)))
        END IF
      END SELECT   
     END SELECT
   END DO  
END SUBROUTINE