! BLOCK DIAGONAL ==============================================================
! **** PURPOSE **** 
! INPUT A SPARSE MATRIX, IT FINDS THE GROUP OF EACH VECTOR AND RELABEL YOUR
! SPAESR MATRIX TO MAKE BLOCK DIAGONAL FORM
! **** VARIABLES ****
! [A_SP]: INTEGER, 3X(M+1), M=TOT NZ MATRIX ELEMENT OF A 
!	<= THE SPARSE MATRIX
!	=> THE RELABELED SPARSE MATRIX WITH BLOCK DIAGONAL FORM            
! [VEC_GRP]: INTEGER, 2XN, N=TOT VECTORS
!	=> VECTOR REORDERED SEQUENCE AND ITS CORRESPONDING GROUP
! **** VERSION ****
! 2/6/2014 FIRST BUILT 
! **** COMMENT ****
! 1. SPARSE
! BECAUSE A BLCOK DIAGONABLE MATRIX IS EXPECTED TO BE SPARSE. SO THIS CODE
! DOES ITS JOB BASED ON SPARSE FORM. IF NEEDED, USE PI_SPARSE_FULL TO CONVERT
! YOUR FULL MATRIX TO SPARSE FORM.
! 2. THE SPARSE MATRIX
! THE SPARSE MATRIX WILL BE RELABELED (BUT THE VALUE INDEX WON'T)
! BE CAUTIOUS IF YOU WANT TO KEEP YOUR ORIGINAL DATA. 

SUBROUTINE PI_SP_BLKDIAG(A_SP,A_SP_DIM,VEC_GRP,VEC_GRP_DIM)
	IMPLICIT NONE
	! DIMENSION 
	INTEGER :: A_SP_DIM(2), VEC_GRP_DIM(2)
	! INPUT/OUTPUT
	INTEGER, INTENT(INOUT) :: A_SP(A_SP_DIM(1),A_SP_DIM(2))
	! OUTPUT
	INTEGER, INTENT(OUT) :: VEC_GRP(VEC_GRP_DIM(1),VEC_GRP_DIM(2))
	! DUMMY
	INTEGER :: N, GRP_COUNT, TMP_I_N1, TMP_I_N2, TMP_I_N3
	
	! VARIABLE INITIALIZATION
	VEC_GRP=0;
	FORALL(N=1:A_SP(1,1)) VEC_GRP(2,N)=N ! (GROUP_LABEL, VECTOR_INDEX)
	DO N=2,A_SP_DIM(2)
		IF(VEC_GRP(1,A_SP(2,N))==0) THEN
			VEC_GRP(1,A_SP(2,N))=A_SP(1,N)
		ELSE
			WHERE(VEC_GRP(1,:)==VEC_GRP(1,A_SP(2,N)))
				VEC_GRP(1,:)=A_SP(1,N)
			END WHERE
		END IF
	END DO
	CALL PI_LSORT_IMAT(VEC_GRP,SHAPE(VEC_GRP),'C','I') ! GIVE YOU RERODER
	
	! CALCULATE AND RELABEL GROUP
	GRP_COUNT=1
	DO N=1,A_SP(1,1)-1
		IF (VEC_GRP(1,N+1)/=VEC_GRP(1,N)) THEN
			VEC_GRP(1,N)=GRP_COUNT
			GRP_COUNT=GRP_COUNT+1
		ELSE
			VEC_GRP(1,N)=GRP_COUNT
		END IF
	END DO
	VEC_GRP(1,A_SP(1,1))=GRP_COUNT
	
	! RELABEL SPARSE MATRIX BASED ON NEW ORDERING
	TMP_I_N1=0
	TMP_I_N2=0
	TMP_I_N3=1
	
	DO N=2,A_SP_DIM(2)
		!# SEARCHING FOR INDEX
		IF (TMP_I_N3==1) THEN
			CALL PI_FIND_VECT(VEC_GRP(2,:)==A_SP(1,N),SHAPE(VEC_GRP(2,:)),TMP_I_N1,1)
		END IF
		CALL PI_FIND_VECT(VEC_GRP(2,:)==A_SP(2,N),SHAPE(VEC_GRP(2,:)),TMP_I_N2,1)
		
		!# DETERMINE WHETHER NEXT SEARCH IS NEEDED
		IF (N<A_SP_DIM(2)) THEN
			IF (A_SP(1,N+1)==A_SP(1,N)) THEN
				TMP_I_N3=0
			ELSE 
				TMP_I_N3=1
			END IF
		END IF
		A_SP(1,N)=TMP_I_N1
		A_SP(2,N)=TMP_I_N2
	END DO
	
	CALL PI_LSORT_IMAT(A_SP(:,2:),SHAPE(A_SP(:,2:)),'C','I')
END SUBROUTINE
	
	
	
	
	
	
	
	
	