! SPARSE_SIZE ====================================================================  
! **** PURPOSE ****
! THIS CODE OUTPUTS YOU THE SIZE OF THE UPPER TRIANGLE OF YOUR A SYMMETRY MATRIX 
! IN SPARSE FORM
! **** INPUT VARIABLES ****
! [A]: REAL, NXN, THE FULL SYMMETRY MATRIX
! **** OUTPUT VARIABLES ****
! [SP_SIZE]: INTEGER, 1, HOW MANY NON-ZERO ELEMENTS IN THE UPPER TRIANGLE
! **** VERSION ****
! FEB/5/2014
! **** COMMENT **** 
! THIS CODE IS TO HELP YOU ANNOUNCE THE SIZE OF YOUR SPARSE MATRIX IN MEMORY

SUBROUTINE PI_SYSP_SIZE(A,A_DIM,SP_SIZE)
	IMPLICIT NONE
	! DIMENSION
	INTEGER, INTENT(IN) :: A_DIM(2)
	! INPUT
	REAL, INTENT(IN) :: A(A_DIM(1),A_DIM(2))
	! OUTPUT
	INTEGER, INTENT(OUT) :: SP_SIZE
	! LOCAL(DUMMY)
	INTEGER :: N, M
	! LOCAL(VALUE)
	INTEGER :: ZERO=0.00001
	
	SP_SIZE=0
	CALL PI_CLEAN_RMAT(A,A_DIM,ZERO)
	SP_SIZE=0
	DO N=1,A_DIM(1)
		DO M=N,A_DIM(2)
			IF (ABS(A(N,M))>ZERO) THEN
				SP_SIZE=SP_SIZE+1
			END IF
		END DO
	END DO
END SUBROUTINE

! HERMITIAN MATRIX ============================================================

SUBROUTINE PI_HESP_SIZE(A,A_DIM,SP_SIZE)
	IMPLICIT NONE
	! DIMENSION
	INTEGER, INTENT(IN) :: A_DIM(2)
	! INPUT
	COMPLEX, INTENT(IN) :: A(A_DIM(1),A_DIM(2))
	! OUTPUT
	INTEGER, INTENT(OUT) :: SP_SIZE
	! LOCAL(DUMMY)
	INTEGER :: N, M
	! LOCAL(VALUE)
	INTEGER :: ZERO=0.00001
	
	SP_SIZE=0
	CALL PI_CLEAN_CMAT(A,A_DIM,ZERO)
	SP_SIZE=0
	DO N=1,A_DIM(1)
		DO M=N,A_DIM(2)
			IF (ABS(A(N,M))>ZERO) THEN
				SP_SIZE=SP_SIZE+1
			END IF
		END DO
	END DO
END SUBROUTINE
		