! FOCK STATE CONVERT ===========================================================  
! **** PURPOSE ****
! CONVERT THE FOCK_OCCUO FROM PI_FOCK_OCCUP (MUST USE 'TOTAL' OUT_FORM) TO FORMAL 
! FOCK OCCUPATION REPRESENTATION.  
! **** INPUT VARIABLES ****
! [OCCUP_NUM]: INTEGER, (2)X(TOT_SITE), THE SAME DEFINITION AS PI_FOCK_OCCUP
! [FOCK_OCCUP]: INTEGER, (TOT_COMB)X(TOT_PT), SHOULD GET FROM PI_FOCK_OCCUP
! [PH_TRANS]: INTEGER, 1X(TOT_SITE), TELLS PARTICLES OR HOLES FOR EACH SITE
! **** OUTPUT VARIABLES ****
! [FOCK_STATE]: INTEGER, (TOT_COMB)X(TOT_SINGLE_PT_STATE), THE FOCK STATE
! **** VERSION ****
! 1/24/2014 FIRST BUILT 
! **** COMMENT **** 
! 1. FUNCTION
! USING FORMAL FOCK STATE CAN FIX THE SIZE OF YOUR FOCK STATE MATRIX. IT IS HELPFUL
! FOR FURTHER CALCULATIONS
! 2. PH_TRANS
! THIS CODE REQIRES YOU TO SPECIFY HOW DID YOU LABEL YOUR OCCUPATIONS IN FOCK_OCCUP
! ON EACH SITE, +1(HOLE), -1(ELECTRON). IF IT IS HOLE, THE CODE ASSIGNED 0 FOR THE
! LABELED STATES AND 1 FOR NON-LABEL STATES AND VICE VERSA.

SUBROUTINE PI_FOCK_CONVERT(OCCUP_NUM,OCCUP_NUM_DIM,FOCK_OCCUP,FOCK_OCCUP_DIM,PH_TRANS,PH_TRANS_DIM,FOCK_STATE,FOCK_STATE_DIM)
  IMPLICIT NONE
  ! DIMENSION 
  INTEGER, INTENT(IN) :: OCCUP_NUM_DIM(2),FOCK_OCCUP_DIM(2), PH_TRANS_DIM, FOCK_STATE_DIM(2)
  ! INPUT
  INTEGER, INTENT(IN) :: OCCUP_NUM(OCCUP_NUM_DIM(1),OCCUP_NUM_DIM(2))
  INTEGER, INTENT(IN) :: FOCK_OCCUP(FOCK_OCCUP_DIM(1),FOCK_OCCUP_DIM(2)) 
  INTEGER, INTENT(IN) :: PH_TRANS(PH_TRANS_DIM)
  ! OUTPUT
  INTEGER, INTENT(OUT) :: FOCK_STATE(FOCK_STATE_DIM(1),FOCK_STATE_DIM(2))
  ! LOCAL(DUMMIES)
  INTEGER :: N, M, P
  ! LOCAL(VALUES)
  INTEGER :: TOT_COMB, TOT_LEVEL, TOT_SITE, F_INDEX, TOT_PT   
  ! LOCAL(ARRAYS)
  INTEGER :: SITE_LEVEL_RANGE(2,OCCUP_NUM_DIM(2))
  ! LOCAL(ALLOCATABLES)
  ! N/A
  ! VARIABLE INITIALIZATION
  FOCK_STATE=0; ! OUTPUT
  TOT_COMB=0; TOT_LEVEL=0; TOT_SITE=0; F_INDEX=0; TOT_PT=0! VALUES
  SITE_LEVEL_RANGE=0; ! ARRAYS
  
  ! PROGRAM START------------------------
  
  ! CHECK IF FOCK_COOUP IS IN 'TOTAL' FORM
  IF (COUNT(FOCK_OCCUP(:,1)==1)>1) THEN
    WRITE(*,*) "ERROR IN PI_FOCK_CONVERT! FOCK_OCCUP MUST BE IN 'TOTAL' FORM! "
    RETURN
  END IF
  
  ! GENERATE ALL NEEDED VARIABLES  
  TOT_COMB=FOCK_OCCUP_DIM(2)
  TOT_LEVEL=MAXVAL(FOCK_OCCUP(:,TOT_COMB))
  TOT_SITE=OCCUP_NUM_DIM(2)
  TOT_PT=SUM(OCCUP_NUM(2,:))
  SITE_LEVEL_RANGE(1,1)=1; SITE_LEVEL_RANGE(2,1)=OCCUP_NUM(1,1);
  IF (TOT_SITE>1) THEN
   DO N=2,TOT_SITE
      SITE_LEVEL_RANGE(1,N)=SITE_LEVEL_RANGE(2,N-1)+1
      SITE_LEVEL_RANGE(2,N)=SITE_LEVEL_RANGE(2,N-1)+OCCUP_NUM(1,N)
    END DO
  END IF

  ! GENERATE VACUUM STATE BASED ON PARTICLE-HOLE INPUT
  DO N=1,TOT_SITE
    SELECT CASE(PH_TRANS(N))
    CASE(+1)
      FOCK_STATE(SITE_LEVEL_RANGE(1,N):SITE_LEVEL_RANGE(2,N),:)=1   
    CASE(-1)
      FOCK_STATE(SITE_LEVEL_RANGE(1,N):SITE_LEVEL_RANGE(2,N),:)=0
    END SELECT
  END DO

  DO N=1,TOT_COMB
      DO M=1,TOT_PT
        F_INDEX=FOCK_OCCUP(M,N)
        SELECT CASE(FOCK_STATE(F_INDEX,N))
        CASE(+1)
          FOCK_STATE(F_INDEX,N)=0
        CASE(0)
          FOCK_STATE(F_INDEX,N)=1
        END SELECT
      END DO
  END DO
END SUBROUTINE