! THIS CODE CAN DIAGONALIZE A GIVEN REAL OR COMPLEX HERMITIAN MATRIX
! IT CALLS THE LAPACK FUNCTION TO CALCULATES. THIS CODE JUST PROVIDES
! YOU A EASIER INTERFACE TO USE THOSE FUNCTIONS

SUBROUTINE PI_EIG_RMAT(A,A_DIM,EVAL,EVAL_DIM,EVECT,EVECT_DIM)
	IMPLICIT NONE
	! DIMENSION
	INTEGER, INTENT(IN) :: A_DIM(2), EVAL_DIM, EVECT_DIM(2)
	! INPUT
	REAL, INTENT(IN) :: A(A_DIM(1),A_DIM(2))
	! OUTPUT
	REAL, INTENT(OUT) :: EVAL(EVAL_DIM)
	REAL, INTENT(OUT) :: EVECT(EVECT_DIM(1),EVECT_DIM(2))
	! LOCAL (VALUE)
	INTEGER :: INFO, LWORK
	! LOCAL (ARRAY)
	REAL, ALLOCATABLE :: WORK(:)
	
	! CHECK INPUT
	IF (SUM(ABS(EVECT_DIM-A_DIM))/=0) THEN
		WRITE(*,*) "ERROR IN PI_EIG_RMAT! DIMENSION INCONSISETNT!"
	END IF
	
	! VARIABLE INITIALIZATION ------------------------------------------------- 
	LWORK=-1
	EVAL=0; EVECT=A
	
	! SEARCHING OPTIMAL VALUE FOR LWORK ---------------------------------------
	ALLOCATE(WORK(MAX(1,LWORK)))
    CALL SSYEV('V','L',EVECT_DIM(1),EVECT,EVECT_DIM(1),EVAL,WORK,LWORK,INFO)
	LWORK=NINT(WORK(1))
	LWORK=LWORK+1
	DEALLOCATE(WORK)
    ALLOCATE(WORK(MAX(1,LWORK)))
	
	! DIAGONALIZATION
	CALL SSYEV('V','L',EVECT_DIM(1),EVECT,EVECT_DIM(1),EVAL,WORK,LWORK,INFO)
	IF (INFO/=0) THEN
		WRITE(*,*) "ERROR IN PI_EIG_RMAT! SSYEV GET INFO/=0!"
		RETURN
	END IF
END SUBROUTINE

! CMAT ========================================================================

SUBROUTINE PI_EIG_CMAT(A,A_DIM,EVAL,EVAL_DIM,EVECT,EVECT_DIM)
	IMPLICIT NONE
	! DIMENSION
	INTEGER, INTENT(IN) :: A_DIM(2), EVAL_DIM, EVECT_DIM(2)
	! INPUT
	COMPLEX, INTENT(IN) :: A(A_DIM(1),A_DIM(2))
	! OUTPUT
	REAL, INTENT(OUT) :: EVAL(EVAL_DIM)
	COMPLEX, INTENT(OUT) :: EVECT(EVECT_DIM(1),EVECT_DIM(2))
	! LOCAL (VALUE)
	INTEGER :: INFO, LWORK
	REAL :: RWORK(3*A_DIM(1)-2)
	! LOCAL (ARRAY)
	REAL, ALLOCATABLE :: WORK(:)
	
	! CHECK INPUT
	IF (SUM(ABS(EVECT_DIM-A_DIM))/=0) THEN
		WRITE(*,*) "ERROR IN PI_EIG_CMAT! DIMENSION INCONSISETNT!"
	END IF
	
	! VARIABLE INITIALIZATION ------------------------------------------------- 
	LWORK=-1
	EVAL=0; EVECT=A
	
	! SEARCHING OPTIMAL VALUE FOR LWORK ---------------------------------------
	ALLOCATE(WORK(MAX(1,LWORK)))
    CALL CHEEV('V','L',EVECT_DIM(1),EVECT,EVECT_DIM(1),EVAL,WORK,LWORK,RWORK,INFO)
	LWORK=NINT(WORK(1))
	LWORK=LWORK+1
	DEALLOCATE(WORK)
    ALLOCATE(WORK(MAX(1,LWORK)))
	
	! DIAGONALIZATION
	CALL CHEEV('V','L',EVECT_DIM(1),EVECT,EVECT_DIM(1),EVAL,WORK,LWORK,RWORK,INFO)
	IF (INFO/=0) THEN
		WRITE(*,*) "ERROR IN PI_EIG_CMAT! CHEEV GET INFO/=0!"
		RETURN
	END IF
END SUBROUTINE